### ISSUE TITLE
Invalid Syntax in setup.py line 17

### ISSUE THREAD

**Issue by nypdmax** [chuanconggao/RegexOrder#2]
I tried to install regexorder from pypi but encountered this issue.

```
download_url=f"{url}/tarball/{version}",
                                              ^
SyntaxError: invalid syntax

```

The error disappeared after I removed "f".

I am using windows subsystem for linux with a ubuntu 16.04 executable environment.

**Comment by chuanconggao** [comment]
It is because f-string is only supported since Python 3.6. Please upgrade your Python to use this library.

As Python 3.7 is already released, there is no plan to support any version prior to Python 3.6.
